name: Deno Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x

    - name: Set environment variables
      run: |
        echo "GPT_API_KEY=${{ secrets.GPT_API_KEY }}" >> $GITHUB_ENV
        # Add more environment variables as needed

    - name: Run Tests
      run: deno test -A
